import { ThemedHTML } from "./themes/themedHTML";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemedHTML lang="en">
      <body className="dark:bg-slate-800 dark:text-white">{children}</body>
    </ThemedHTML>
  );
}
